enum Role {
    ROLE_GUEST = "ROLE_GUEST",
    ROLE_STUDENT = "ROLE_STUDENT",
    ROLE_INSTRUCTOR = "ROLE_INSTRUCTOR",
    ROLE_BUSINESS = "ROLE_BUSINESS",
    ROLE_MANAGER = "ROLE_MANAGER",
    ROLE_ADMIN = "ROLE_ADMIN",
}

export default Role;
